# Generated by Django 4.2 on 2023-06-08 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_alter_acao_close_alter_acao_high_alter_acao_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
