# Generated by Django 4.2 on 2023-06-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_acao_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='user',
            new_name='user_id',
        ),
    ]
