# Generated by Django 4.2 on 2023-06-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_user_acao_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='user_id',
        ),
    ]
