# Generated by Django 4.2 on 2023-06-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_acao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='user',
        ),
    ]
